#!/usr/bin/env python
import argparse
import importlib
import sys

parser = argparse.ArgumentParser(add_help=False)
parser.add_argument("command", type=str)

options, args = parser.parse_known_args()

command = importlib.import_module('rocketz.control.%s' % options.command)
command.execute(options.command, args)

