MEDIA_BUNDLES = (
    ( 'contrib.js',
        'js/lib/jquery-1.7.2.js',
        'js/lib/kinetic-v3.10.4.js',
        'js/lib/pixelimage.coffee',
        'js/lib/particles.coffee',
        'js/lib/vec2.coffee',
    ),
    ( 'app.js',
        'js/namespace.js',
        'js/config.js',
        'js/app.js',
        'js/src/stage.js',
        'js/src/utils.js',
        'js/src/ws.js',
        'js/src/layers/background.js',
        'js/src/objects/gameObject.coffee',
        'js/src/objects/ellipse.coffee',
        'js/src/objects/polygon.coffee',
        'js/src/objects/spaceShip.coffee',
        'js/src/layers/battle.coffee',
        'js/src/layers/world.coffee',
        'js/src/viewport.coffee',
    ),
)


