MEDIA_BUNDLES = (
    ( 'contrib.js',
        'js/lib/jquery-1.7.2.js',
        'js/lib/underscore-1.3.3.js',
        'js/lib/kinetic-v3.10.4.js',
        'js/lib/pixelimage.coffee',
        'js/lib/particles.coffee',
        'js/lib/vec2.coffee',
    ),
    ( 'app.js',
        'js/namespace.coffee',
        'js/config.coffee',
        'js/app.coffee',
        'js/src/utils.coffee',
        'js/src/sockets/rocketSocket.coffee',
        'js/src/objects/gameObject.coffee',
        'js/src/objects/ellipse.coffee',
        'js/src/objects/polygon.coffee',
        'js/src/objects/spaceShip.coffee',
        'js/src/layers/background.coffee',
        'js/src/layers/battle.coffee',
        'js/src/layers/world.coffee',
        'js/src/basicViewport.coffee',
    ),
)


